server:
  port: 8082
logging:
  level:
    ROOT: INFO
spring:
  application:
    admin:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans

app.message: "Test Props msg_test"

messager:
  message: "Hello from Messager"